#!/usr/bin/env nu
# Regenerate GALLERY.md from the live registries (themes, styles, looks) so the
# counts, lists and tables can never go stale.
#
#   nu scripts/gen_gallery.nu           # rewrite GALLERY.md
#   nu scripts/gen_gallery.nu --check   # exit 1 if GALLERY.md is out of date (used by test.nu)
source ../nushell-prompt.nu

# Markdown for a list of names: `a` · `b` · …  (wrapped by word at ~78 cols)
def wrap-names [names: list<string>] {
    mut lines = []
    mut cur = ""
    for n in ($names | each {|x| $"`($x)`" }) {
        let next = (if ($cur | is-empty) { $n } else { $"($cur) · ($n)" })
        if ($next | str length) > 76 {
            $lines = ($lines | append $cur)
            $cur = $n
        } else { $cur = $next }
    }
    $lines | append $cur | str join " ·\n"
}

def render [] {
    let themes = (theme-list)
    let builtin = ($themes | where {|t| $t not-in (user-theme-names) })
    let light = ($builtin | where {|t| (theme-get $t).palette.light })
    let dark = ($builtin | where {|t| $t not-in $light })
    let styles = (style-defs)
    let looks = (presets)
    let nt = ($builtin | length)
    let ns = ($styles | length)
    let nl = ($looks | length)

    let style_rows = ($styles | each {|s| $"| `($s.name)` | ($s.desc) |" } | str join "\n")
    let look_rows = ($looks | each {|l| $"| `($l.name)` | ($l.theme) | ($l.style) |" } | str join "\n")

    $"# nuance — gallery

Every **theme**, **style** and **look** at a glance.
Usage & commands are in the [main README]\(README.md#theming--styling).

- [Themes \(($nt))]\(#themes-($nt))
- [Prompt styles \(($ns))]\(#prompt-styles-($ns))
- [Looks \(($nl))]\(#looks-($nl))

> This file is generated by `nu scripts/gen_gallery.nu` \(`just gallery`\) from
> the theme, style and look registries — edit those, not this file.

---

## Themes \(($nt))

Every theme's palette at a glance:

![theme swatches]\(docs/gallery-themes.gif)

A selection with recolored syntax + tables:

![themes]\(docs/themes.gif)

More of the newer themes:

![more themes]\(docs/themes-more.gif)

Light themes on a light terminal background:

![light themes]\(docs/light.gif)

**Dark \(($dark | length)):**
(wrap-names $dark)

**Light \(($light | length)):**
(wrap-names $light)

**Yours:** anything you `nuance import` \(Ghostty, kitty, Alacritty, base16).

The game-flavoured themes \(`coin-rush`, `sunny-course`, `cave-course`,
`greenfield`, `phosphor`, `inferno`, `gilded-ruin`, `belle-epoque`, `phantom`,
`cavern-hush`, `test-chamber`, `ember`, `meadow`, `dojo`, `underworld`, `summit`,
`rain-noir`, `blocky`, `cyberpunk`) are original, genre-inspired palettes with
generic names — see the note on trademarks in the README.

---

## Prompt styles \(($ns))

Every style rendered once:

![all styles]\(docs/gallery-styles.png)

Cycling a few live:

![styles]\(docs/styles.gif)

| Style | Description |
|-------|-------------|
($style_rows)

Game-inspired looks \(platformer, retro terminal, soulslike, heist, farm sim,
fighting game, roguelike, sandbox, cyberpunk …):

![game looks]\(docs/games.gif)

---

## Looks \(($nl))

A **look** is a curated theme + style pairing.

![looks]\(docs/demo.gif)

| Look | Theme | Style |
|------|-------|-------|
($look_rows)
"
}

def main [--check] {
    let target = ($env.FILE_PWD | path dirname | path join "GALLERY.md")
    let out = (render)
    if $check {
        let cur = (try { open --raw $target } catch { "" })
        if $cur != $out {
            print -e "GALLERY.md is out of date — run: nu scripts/gen_gallery.nu"
            exit 1
        }
        return
    }
    $out | save -f $target
    print $"✓ GALLERY.md regenerated — (theme-list | length) themes, (prompt-styles | length) styles, (presets | length) looks"
}
